/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:02581382-a287-4c3c-8160-18e52ecec9fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6LeUEGACZ",
    "aws_user_pools_web_client_id": "25ainsh9rdub0el9ojjcmgfpu0",
    "oauth": {}
};


export default awsmobile;
